// Indicative regional corridors, not a timetable. Minutes are hand estimates
// between the listed city stops (intermediate village stops are omitted).
// Station names are explicit where they differ from the municipality name.
export const TRANSFER_MINUTES = 12;
// Municipalities without Stadt status and district stations may be junctions,
// but must never become selectable cities or be added to the Destatis roster.
export const TRANSIT_STOPS = new Set(['Altenbeken','Dülken','Wickede (Ruhr)','Haste','Barnstorf','Rastede','Hude','Bad Zwischenahn','Ottersberg','Schladen-Werla','Kreiensen','Guxhagen','Wabern','Erndtebrück','Finnentrop','Schalksmühle','Eitorf','Windeck','Horrem','Engelskirchen','Marienheide','Kall']);
export const NETWORK_SOURCES = [
  'https://infoportal.mobil.nrw/information-service/regionalverkehrsplan-nrw.html',
  'https://www.bahn.de/service/fahrplaene/streckennetz'
];
// name, city sequence, minutes between successive cities
export const CORRIDORS = [
  ['westfalen-main','Bielefeld;Gütersloh;Rheda-Wiedenbrück;Oelde;Beckum|Neubeckum;Ahlen;Hamm',[15,10,10,5,10,10]],
  ['bielefeld-minden','Bielefeld;Herford;Löhne;Bad Oeynhausen;Porta Westfalica;Minden',[10,10,5,7,8]],
  ['ravensberger','Bielefeld;Halle (Westf.);Borgholzhausen;Dissen am Teutoburger Wald;Osnabrück',[25,15,5,25]],
  ['senne','Bielefeld;Schloß Holte-Stukenbrock;Paderborn',[25,35]],
  ['lippe','Herford;Bad Salzuflen;Lage;Detmold;Altenbeken',[12,13,15,25]],
  ['lemgo','Bielefeld;Lage;Lemgo',[30,15]],
  ['minden-nienburg','Minden;Petershagen|Petershagen-Lahde;Nienburg (Weser)',[12,38]],
  ['hildesheim-weser','Löhne;Vlotho;Rinteln;Hessisch Oldendorf;Hameln;Elze;Hildesheim',[12,15,12,15,25,15]],
  ['hannover-minden','Minden;Bückeburg;Stadthagen;Wunstorf;Hannover',[10,20,20,20]],
  ['osnabrueck-loehne','Löhne;Bünde;Melle;Osnabrück',[10,15,20]],
  ['rahden','Bünde;Lübbecke;Espelkamp;Rahden',[30,10,10]],
  ['re2-north','Osnabrück;Lengerich|Lengerich (Westf);Münster',[15,25]],
  ['re7','Münster;Drensteinfurt;Hamm;Unna;Schwerte|Schwerte (Ruhr);Hagen;Ennepetal;Schwelm;Wuppertal;Solingen;Leverkusen|Leverkusen Opladen;Köln',[15,15,12,15,12,12,8,12,15,15,20]],
  ['ruhr-main','Hamm;Kamen;Dortmund;Bochum;Essen;Mülheim an der Ruhr|Mülheim (Ruhr) Hbf;Duisburg;Düsseldorf;Köln;Düren;Eschweiler|Eschweiler Hbf;Stolberg (Rhld.)|Stolberg (Rheinl) Hbf;Aachen',[12,13,12,15,8,10,18,30,25,15,8,15]],
  ['ruhr-north','Dortmund;Castrop-Rauxel|Castrop-Rauxel Hbf;Herne;Gelsenkirchen;Essen;Duisburg',[15,8,12,12,20]],
  ['ruhr-rhein','Gelsenkirchen;Oberhausen;Duisburg',[15,10]],
  ['re6-rhein','Düsseldorf;Neuss|Neuss Hbf;Dormagen;Köln',[12,12,20]],
  ['re4','Düsseldorf;Neuss;Mönchengladbach;Hückelhoven|Hückelhoven-Baal;Geilenkirchen;Herzogenrath;Aachen',[12,18,25,15,15,12]],
  ['re10','Düsseldorf;Krefeld;Kempen;Geldern;Kevelaer;Goch;Kleve',[30,15,20,10,15,15]],
  ['re13','Mönchengladbach;Viersen;Nettetal|Kaldenkirchen',[10,18]],
  ['re19','Oberhausen;Dinslaken;Voerde (Niederrhein)|Voerde (Niederrhein);Wesel;Rees|Empel-Rees;Emmerich am Rhein|Emmerich',[12,8,10,20,15]],
  ['bocholt','Wesel;Hamminkeln;Bocholt',[12,15]],
  ['re2-south','Münster;Haltern am See;Recklinghausen;Gelsenkirchen',[25,15,15]],
  ['rb50','Münster;Werne|Werne a d Lippe;Lünen|Lünen Hbf;Dortmund',[35,10,15]],
  ['rb51','Dortmund;Lünen;Selm;Dülmen;Coesfeld',[15,15,20,15]],
  ['rb63','Münster;Billerbeck;Coesfeld',[30,15]],
  ['rb64','Münster;Steinfurt|Steinfurt-Burgsteinfurt;Gronau (Westf.)|Gronau (Westf)',[35,25]],
  ['rb67','Münster;Telgte;Warendorf;Rheda-Wiedenbrück;Bielefeld',[15,15,35,25]],
  ['rb45','Coesfeld;Dorsten',[45]],
  ['re14','Essen;Bottrop|Bottrop Hbf;Gladbeck|Gladbeck West;Dorsten;Borken',[15,8,20,25]],
  ['rb43','Dortmund;Castrop-Rauxel|Castrop-Rauxel Hbf;Herne;Gladbeck;Dorsten',[20,10,35,20]],
  ['re15','Münster;Emsdetten;Rheine;Lingen (Ems)|Lingen (Ems);Meppen;Papenburg;Leer (Ostfriesland)|Leer (Ostfriesl);Emden|Emden Hbf',[25,10,25,15,25,15,15]],
  ['re62','Osnabrück;Ibbenbüren;Hörstel;Rheine',[20,10,10]],
  ['rb61','Bielefeld;Herford;Bünde;Melle;Osnabrück;Ibbenbüren;Hörstel;Rheine;Bad Bentheim',[10,15,15,20,20,10,10,20]],
  ['re17','Hagen;Schwerte;Fröndenberg/Ruhr;Arnsberg;Meschede;Olsberg;Brilon|Brilon Wald;Marsberg;Warburg;Kassel',[12,15,25,20,15,10,25,20,35]],
  ['re57','Dortmund;Fröndenberg/Ruhr|Fröndenberg;Wickede (Ruhr);Arnsberg;Meschede;Olsberg;Winterberg',[30,10,20,20,15,35]],
  ['hellweg','Hamm;Soest;Lippstadt;Geseke;Paderborn;Altenbeken;Warburg',[25,15,10,20,15,25]],
  ['rb84','Paderborn;Altenbeken;Bad Driburg;Brakel;Höxter;Holzminden',[15,10,12,23,12]],
  ['rb72','Herford;Bad Salzuflen;Lage;Detmold;Altenbeken;Paderborn',[12,13,15,25,15]],
  ['rb73','Lage;Lemgo',[15]],
  ['s5-hameln','Hannover;Springe;Bad Münder am Deister|Bad Münder (Deister);Hameln;Bad Pyrmont;Lügde;Steinheim;Altenbeken;Paderborn',[30,10,15,20,5,15,20,15]],
  ['s1-deister','Hannover;Seelze;Wunstorf;Haste;Bad Nenndorf;Barsinghausen;Hannover',[12,12,10,5,18,35]],
  ['s2-north','Hannover;Langenhagen|Langenhagen Mitte;Neustadt am Rübenberge;Nienburg (Weser)',[10,20,25]],
  ['re8','Hannover;Neustadt am Rübenberge;Nienburg (Weser);Verden (Aller);Achim;Bremen;Osterholz-Scharmbeck;Bremerhaven|Bremerhaven Hbf',[20,20,25,15,15,20,30]],
  ['re9','Osnabrück;Diepholz;Barnstorf;Twistringen;Bassum;Bremen',[30,10,15,10,25]],
  ['rb58','Osnabrück;Bramsche;Bersenbrück;Quakenbrück;Lohne (Oldenburg)|Lohne (Oldb);Vechta;Wildeshausen;Delmenhorst;Bremen',[20,20,15,20,12,30,25,12]],
  ['re18','Osnabrück;Bramsche;Quakenbrück;Cloppenburg;Oldenburg (Oldenburg);Rastede;Varel;Wilhelmshaven|Wilhelmshaven Hbf',[20,35,20,35,15,20,20]],
  ['bremen-oldenburg','Bremen;Delmenhorst;Hude;Oldenburg (Oldenburg);Bad Zwischenahn;Westerstede|Westerstede-Ocholt;Leer (Ostfriesland);Emden',[12,15,15,12,12,30,15]],
  ['rs4','Bremen;Delmenhorst;Hude;Elsfleth;Brake (Unterweser)|Brake (Unterweser);Nordenham',[12,15,15,15,20]],
  ['re4-north','Bremen;Ottersberg;Rotenburg (Wümme);Buchholz in der Nordheide|Buchholz (Nordheide);Hamburg',[20,15,25,30]],
  ['re2-hannover','Hannover;Langenhagen;Burgwedel|Großburgwedel;Celle;Uelzen;Lüneburg;Winsen (Luhe)|Winsen (Luhe);Hamburg',[10,12,20,40,25,15,25]],
  ['re10-harz','Hannover;Sarstedt;Hildesheim;Salzgitter|Salzgitter-Ringelheim;Goslar;Bad Harzburg',[15,15,25,20,15]],
  ['re70','Hannover;Lehrte;Peine;Braunschweig',[12,18,20]],
  ['re30','Hannover;Lehrte;Gifhorn;Wolfsburg',[12,25,15]],
  ['re60','Braunschweig;Helmstedt;Magdeburg',[25,40]],
  ['rb42','Braunschweig;Wolfenbüttel;Schladen-Werla|Schladen (Harz);Goslar',[12,20,25]],
  ['re2-south-hannover','Hannover;Elze;Alfeld (Leine)|Alfeld (Leine);Kreiensen;Northeim;Göttingen',[25,15,20,12,15]],
  ['rb82','Göttingen;Northeim;Kreiensen;Seesen;Langelsheim;Goslar;Bad Harzburg',[15,12,20,15,10,15]],
  ['einbeck','Kreiensen;Einbeck',[10]],
  ['rb80','Göttingen;Northeim;Herzberg am Harz|Herzberg (Harz);Bad Lauterberg im Harz|Bad Lauterberg im Harz Barbis;Bad Sachsa;Ellrich;Nordhausen',[15,30,10,10,10,15]],
  ['re11-hessen','Warburg;Hofgeismar;Kassel',[20,20]],
  ['re30-hessen','Kassel;Baunatal|Baunatal-Guntershausen;Guxhagen;Melsungen;Rotenburg a. d. Fulda|Rotenburg a d Fulda;Bebra;Bad Hersfeld;Fulda',[15,8,12,20,7,15,30]],
  ['re98','Kassel;Wabern;Borken (Hessen)|Borken (Hess);Schwalmstadt|Treysa;Stadtallendorf;Kirchhain;Marburg;Gießen|Gießen;Friedberg (Hessen)|Friedberg (Hess);Frankfurt am Main',[25,10,15,20,8,12,20,25,25]],
  ['re16','Siegen;Kreuztal;Hilchenbach;Erndtebrück;Bad Laasphe;Biedenkopf;Marburg',[10,15,25,20,20,40]],
  ['ruhr-sieg','Hagen;Iserlohn|Iserlohn-Letmathe;Altena;Werdohl;Plettenberg;Finnentrop;Lennestadt|Lennestadt-Altenhundem;Kreuztal;Siegen',[15,15,10,10,12,12,25,10]],
  ['iserlohn','Iserlohn|Iserlohn-Letmathe;Iserlohn|Iserlohn',[15]],
  ['rb52','Dortmund;Herdecke;Hagen;Schalksmühle;Lüdenscheid',[20,10,25,15]],
  ['rb53','Dortmund;Schwerte;Iserlohn|Iserlohn',[20,25]],
  ['rb54','Fröndenberg/Ruhr;Menden (Sauerland)|Menden (Sauerland);Balve;Neuenrade',[10,20,10]],
  ['re8-rhein','Köln;Troisdorf;Bonn|Bonn-Beuel;Linz am Rhein|Linz (Rhein);Neuwied;Koblenz',[20,15,25,20,15]],
  ['re9-sieg','Köln;Troisdorf;Siegburg|Siegburg/Bonn;Hennef (Sieg)|Hennef (Sieg);Eitorf;Windeck|Schladern (Sieg);Wissen|Wissen (Sieg);Betzdorf;Siegen',[20,7,7,15,15,10,10,20]],
  ['rhein-left','Köln;Brühl;Bonn;Remagen;Sinzig|Sinzig (Rhein);Andernach;Koblenz',[15,15,20,5,20,15]],
  ['s12','Köln;Frechen|Frechen-Königsdorf;Horrem;Kerpen|Sindorf;Düren',[15,10,5,20]],
  ['rb25','Köln;Rösrath;Overath;Engelskirchen;Gummersbach;Marienheide;Meinerzhagen;Lüdenscheid',[20,15,15,15,12,15,25]],
  ['rb24','Köln;Hürth|Hürth-Kalscheuren;Erftstadt;Euskirchen;Mechernich;Kall',[12,15,15,15,10]],
  ['s7','Wuppertal;Remscheid|Remscheid Hbf;Solingen',[30,25]],
  ['s9','Essen;Velbert|Velbert-Langenberg;Wülfrath|Wülfrath-Aprath;Wuppertal',[25,15,15]],
  ['s6','Essen;Ratingen|Ratingen Ost;Düsseldorf;Langenfeld (Rheinland)|Langenfeld (Rheinl);Leverkusen|Leverkusen Mitte;Köln',[35,20,20,10,20]],
  ['s1-ruhr','Dortmund;Bochum;Essen;Mülheim an der Ruhr;Duisburg;Düsseldorf;Hilden;Solingen',[20,20,10,10,25,20,15]],
  ['s3','Oberhausen;Essen;Hattingen|Hattingen (Ruhr) Mitte',[20,25]],
  ['s5','Dortmund;Witten|Witten Hbf;Wetter (Ruhr)|Wetter (Ruhr);Hagen',[20,10,10]],
  ['s4','Dortmund;Unna',[30]],
  ['s8','Mönchengladbach;Korschenbroich;Neuss;Düsseldorf;Erkrath;Haan|Haan-Gruiten;Wuppertal;Schwelm;Gevelsberg|Gevelsberg Hbf;Hagen',[12,15,15,12,10,15,15,10,15]]
];
